# Generated by Django 2.1.5 on 2020-10-11 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoapi',
            name='user',
        ),
    ]
